modLoader = "javafml"
loaderVersion = "[46,)"
license = "LGPLv3"

[[mods]]
modId = "tweakeroo"
version = "${version}"
displayName = "Tweakerge"
displayURL="https://github.com/ThinkingStudios/Tweakeroo-Forge" #optional
logoFile="icon.png" #optional
credits="masa" #optional
authors="TexTrue, ThinkingStudio" #optional
description = '''
Tweakeroo unofficial forge port.

Adds a bunch of configurable client-side tweaks.
'''

[[dependencies.tweakeroo]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.tweakeroo]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.tweakeroo]]
modId = "malilib"
mandatory = true
versionRange = "[0.1.0,)"
ordering = "NONE"
side = "CLIENT"
